function generatePDFReport(record) {
  const a = record.analysis;
  const scoreColor = a.overall_score >= 75 ? '#2d7d32' : a.overall_score >= 50 ? '#e65100' : '#c62828';

  const suggestionsHtml = (a.suggestions || []).map(s => `
    <div style="border-left:3px solid #1565c0;padding:10px 14px;margin:8px 0;background:#f5f9ff;border-radius:0 6px 6px 0">
      <div style="font-size:11px;font-weight:600;color:#1565c0;text-transform:uppercase;margin-bottom:4px">${s.section || 'General'}</div>
      <div style="font-size:13px;color:#333;margin-bottom:4px"><strong>Issue:</strong> ${s.issue || ''}</div>
      <div style="font-size:13px;color:#333"><strong>Fix:</strong> ${s.fix || ''}</div>
    </div>`).join('');

  const sectionScores = Object.entries(a.section_scores || {}).map(([k, v]) => {
    const label = k.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    const color = v >= 75 ? '#2d7d32' : v >= 50 ? '#e65100' : '#c62828';
    return `<tr>
      <td style="padding:6px 8px;font-size:13px;color:#444">${label}</td>
      <td style="padding:6px 8px">
        <div style="background:#eee;border-radius:4px;height:8px;width:100%">
          <div style="background:${color};width:${v}%;height:8px;border-radius:4px"></div>
        </div>
      </td>
      <td style="padding:6px 8px;font-size:13px;font-weight:600;color:${color};text-align:right">${v}</td>
    </tr>`;
  }).join('');

  const date = new Date(record.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Resume Analysis Report</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #222; max-width: 800px; margin: 0 auto; padding: 32px 24px; }
  h1 { font-size: 24px; color: #1a237e; margin-bottom: 4px; }
  .meta { font-size: 13px; color: #777; margin-bottom: 32px; }
  .score-big { font-size: 64px; font-weight: 700; color: ${scoreColor}; line-height: 1; }
  .score-label { font-size: 14px; color: #777; margin-top: 4px; }
  .verdict { font-size: 15px; color: #444; line-height: 1.6; margin: 16px 0; padding: 14px 18px; background: #f9f9f9; border-radius: 8px; }
  h2 { font-size: 16px; color: #1a237e; border-bottom: 1.5px solid #e3e8f0; padding-bottom: 6px; margin-top: 28px; }
  .tag { display: inline-block; padding: 4px 10px; border-radius: 16px; font-size: 12px; font-weight: 500; margin: 3px; }
  .tag-green { background: #e8f5e9; color: #2d7d32; }
  .tag-red { background: #ffebee; color: #c62828; }
  .tag-blue { background: #e3f2fd; color: #1565c0; }
  ul li { font-size: 13px; margin: 5px 0; line-height: 1.5; }
  table { width: 100%; border-collapse: collapse; }
  @media print { body { padding: 16px; } }
</style>
</head>
<body>
  <h1>📄 Resume Analysis Report</h1>
  <div class="meta">File: ${record.fileName} &nbsp;|&nbsp; Analyzed: ${date}</div>

  <div style="display:flex;align-items:flex-end;gap:24px;margin-bottom:8px">
    <div>
      <div class="score-big">${Math.round(a.overall_score)}</div>
      <div class="score-label">Overall Score / 100</div>
    </div>
    <div style="flex:1">
      <div style="font-size:13px;color:#777">ATS Compatibility</div>
      <div style="font-size:22px;font-weight:600;color:#1565c0">${a.ats_score || '–'}<span style="font-size:14px;color:#999">/100</span></div>
      ${a.job_match_score != null ? `<div style="font-size:13px;color:#777;margin-top:4px">Job Match</div><div style="font-size:22px;font-weight:600;color:#6a1b9a">${Math.round(a.job_match_score)}<span style="font-size:14px;color:#999">/100</span></div>` : ''}
    </div>
  </div>

  <div class="verdict">${a.verdict || ''}</div>

  <h2>Section scores</h2>
  <table>${sectionScores}</table>

  <h2>Strengths</h2>
  <ul>${(a.strengths || []).map(s => `<li>✅ ${s}</li>`).join('')}</ul>

  <h2>Areas to improve</h2>
  <ul>${(a.weaknesses || []).map(s => `<li>⚠️ ${s}</li>`).join('')}</ul>

  <h2>Skill gaps</h2>
  <div>${(a.skill_gaps || []).map(k => `<span class="tag tag-red">${k}</span>`).join('')}</div>

  <h2>Keywords found</h2>
  <div>${(a.keywords_found || []).map(k => `<span class="tag tag-green">${k}</span>`).join('')}</div>

  <h2>Missing keywords</h2>
  <div>${(a.keywords_missing || []).map(k => `<span class="tag tag-red">${k}</span>`).join('')}</div>

  <h2>Actionable suggestions</h2>
  ${suggestionsHtml}

  <div style="margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:12px;color:#aaa;text-align:center">
    Generated by AI Resume Analyzer &nbsp;|&nbsp; ${date}
  </div>
</body>
</html>`;
}

module.exports = { generatePDFReport };
